# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [9]:
### [your code here]
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [19]:
### [your code here]

a = np.random.rand(2,3,5)
a2 = np.random.random((2,3,5))
a3 = np.random.randint(0, 10, (2,3,5)) 


### 4. Print a.


In [23]:
### [your code here]
print(a)

[[[0.80929143 0.8544314  0.16114189 0.35880147 0.81200173]
  [0.90994922 0.7198537  0.6553962  0.23133771 0.33530304]
  [0.50806372 0.73501158 0.59466923 0.47356072 0.80566242]]

 [[0.43194993 0.20540872 0.74736056 0.05989466 0.89276521]
  [0.46773527 0.68661792 0.70859599 0.37644772 0.97717062]
  [0.26339875 0.1127914  0.84290289 0.45324723 0.57766817]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [55]:
### [your code here]
b = np.ones((5, 2, 3),dtype=np.int64)


### 6. Print b.


In [53]:
### [your code here]
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [73]:
### [your code here]
print(a.size == b.size)
print(f"The size for a and b array is : {a.size}")

True
The size for a and b array is : 30



### 8. Are you able to add a and b? Why or why not?


In [76]:
### [your code here]
# When we have two arrays with the same dimension, same size and same shape we can add them
# In this case, both array a and b are 3-dimensional, and as we've checked before, they have the same size, but htey do not have the same shape
# In this case we will need to transpose or reshape one array to match the other's shape
ab_addition= a + b
ab_addition

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [78]:
### [your code here]
c = b.transpose(1,2,0)
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [80]:
### [your code here]
# in order to add to arrays they need to have the same shape, dimension and size. In this case these arrays meet the last two conditions.
# For meet also the shape condition we can transpose one arrray so it matches the other
# that is why this time the addition is working
d = a + c
d

array([[[1.80929143, 1.8544314 , 1.16114189, 1.35880147, 1.81200173],
        [1.90994922, 1.7198537 , 1.6553962 , 1.23133771, 1.33530304],
        [1.50806372, 1.73501158, 1.59466923, 1.47356072, 1.80566242]],

       [[1.43194993, 1.20540872, 1.74736056, 1.05989466, 1.89276521],
        [1.46773527, 1.68661792, 1.70859599, 1.37644772, 1.97717062],
        [1.26339875, 1.1127914 , 1.84290289, 1.45324723, 1.57766817]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [122]:
### [your code here]
print(a)
print()
print(d)
# the d array is just an array full of 1 values added with a, for that all the values in d are 1+a[ijk] 

[[[0.80929143 0.8544314  0.16114189 0.35880147 0.81200173]
  [0.90994922 0.7198537  0.6553962  0.23133771 0.33530304]
  [0.50806372 0.73501158 0.59466923 0.47356072 0.80566242]]

 [[0.43194993 0.20540872 0.74736056 0.05989466 0.89276521]
  [0.46773527 0.68661792 0.70859599 0.37644772 0.97717062]
  [0.26339875 0.1127914  0.84290289 0.45324723 0.57766817]]]

[[[1.80929143 1.8544314  1.16114189 1.35880147 1.81200173]
  [1.90994922 1.7198537  1.6553962  1.23133771 1.33530304]
  [1.50806372 1.73501158 1.59466923 1.47356072 1.80566242]]

 [[1.43194993 1.20540872 1.74736056 1.05989466 1.89276521]
  [1.46773527 1.68661792 1.70859599 1.37644772 1.97717062]
  [1.26339875 1.1127914  1.84290289 1.45324723 1.57766817]]]



### 12. Multiply a and c. Assign the result to e.


In [94]:
### [your code here]
e = a * c
e

array([[[0.80929143, 0.8544314 , 0.16114189, 0.35880147, 0.81200173],
        [0.90994922, 0.7198537 , 0.6553962 , 0.23133771, 0.33530304],
        [0.50806372, 0.73501158, 0.59466923, 0.47356072, 0.80566242]],

       [[0.43194993, 0.20540872, 0.74736056, 0.05989466, 0.89276521],
        [0.46773527, 0.68661792, 0.70859599, 0.37644772, 0.97717062],
        [0.26339875, 0.1127914 , 0.84290289, 0.45324723, 0.57766817]]])



### 13. Does e equal to a? Why or why not?


In [100]:
### [your code here]
np.array_equal(a,e)
# e is equal to a because e = a *c, where c is an 1 value array, every number times 1 equals the number itself, and this is the case for the array as well


True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [110]:
### [your code here]
d_max = np.max(d)
d_max

1.977170621057338

In [112]:
### [your code here]
d_min = np.min(d)
d_min

1.059894656301489

In [114]:
### [your code here]
d_mean = np.mean(d)
d_mean

1.5589476840073309


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [130]:
### [your code here]
f = np.empty((2,3,5))
f

array([[[1.80929143, 1.8544314 , 1.16114189, 1.35880147, 1.81200173],
        [1.90994922, 1.7198537 , 1.6553962 , 1.23133771, 1.33530304],
        [1.50806372, 1.73501158, 1.59466923, 1.47356072, 1.80566242]],

       [[1.43194993, 1.20540872, 1.74736056, 1.05989466, 1.89276521],
        [1.46773527, 1.68661792, 1.70859599, 1.37644772, 1.97717062],
        [1.26339875, 1.1127914 , 1.84290289, 1.45324723, 1.57766817]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [152]:
### [your code here]
for i in range(len(d)):  # Loop over rows
    for j in range(len(d[i])):  # Loop over columns
        for k in range(len(d[i][j])): 
            if (d[i][j][k] > d_min) & (d[i][j][k] < d_mean):
                f[i][j][k] = 25
            elif (d[i][j][k] > d_mean) & (d[i][j][k] < d_max):
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k]=50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [150]:
### [your code here]
print(d)
print()
print(f)

[[[1.80929143 1.8544314  1.16114189 1.35880147 1.81200173]
  [1.90994922 1.7198537  1.6553962  1.23133771 1.33530304]
  [1.50806372 1.73501158 1.59466923 1.47356072 1.80566242]]

 [[1.43194993 1.20540872 1.74736056 1.05989466 1.89276521]
  [1.46773527 1.68661792 1.70859599 1.37644772 1.97717062]
  [1.26339875 1.1127914  1.84290289 1.45324723 1.57766817]]]

[[[ 75.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 25.  25.  75.   0.  75.]
  [ 25.  75.  75.  25. 100.]
  [ 25.  25.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [160]:
### [your code here]
g = np.empty((2,3,5), dtype=object)
for i in range(len(f)):  # Loop over rows
    for j in range(len(f[i])):  # Loop over columns
        for k in range(len(f[i][j])): 
            if f[i][j][k] == 0:
                g[i][j][k] = 'A'
            elif f[i][j][k] == 25:
                g[i][j][k] = 'B'
            elif f[i][j][k] == 50:
                g[i][j][k] = 'C'
            elif f[i][j][k] == 75:
                g[i][j][k] = 'D'
            elif f[i][j][k] == 100:
                g[i][j][k] = 'E'
g

array([[['D', 'D', 'B', 'B', 'D'],
        ['D', 'D', 'D', 'B', 'B'],
        ['B', 'D', 'D', 'B', 'D']],

       [['B', 'B', 'D', 'A', 'D'],
        ['B', 'D', 'D', 'B', 'E'],
        ['B', 'B', 'D', 'B', 'D']]], dtype=object)